version: '3'
services:
  application:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/app
    command: python app.py
    ports:
      - "5000:5000"
    networks:
      - scrum-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: scrumbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: scrumbotagent
    hostname: "scrum-postgres"
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scrum-network

volumes:
  postgres_data:
    driver: local

networks:
  scrum-network:
    driver: bridge
